- name: Check if the file exists in /etc/asterisk
  stat:
    path: "/etc/asterisk/{{ item | basename }}"
  register: file_stat
  with_fileglob:
    - "roles/configure-custom-setting/files/*"
  tags:
    - asterisk-configure

- name: Backup existing configuration files in /etc/asterisk
  command: cp "/etc/asterisk/{{ item | basename }}" "/etc/asterisk/{{ item | basename }}.bak"
  when: file_stat.results[item_index].stat.exists
  loop: "{{ file_stat.results }}"
  loop_control:
    index_var: item_index
  tags:
    - asterisk-configure

- name: Copy all configuration files to /etc/asterisk
  copy:
    src: "{{ item }}"
    dest: "/etc/asterisk/{{ item | basename }}"
    owner: asterisk
    group: asterisk
    mode: "0644"
  with_fileglob:
    - "roles/configure-custom-setting/files/*"
  tags:
    - asterisk-configure

- name: Change permissions of Asterisk-related files and directories
  remote_user: root
  shell: "chmod -R 750 /var/{lib,log,run,spool}/asterisk /usr/lib/asterisk /etc/asterisk"
  args:
    executable: /bin/bash
  tags:
    - asterisk
    - system
