- name: Copy all configuration files to /etc/asterisk (force overwrite)
  copy:
    src: "{{ item }}"
    dest: "/etc/asterisk/{{ item | basename }}"
    owner: asterisk
    group: asterisk
    mode: "0644"
    force: yes
  with_fileglob:
    - "roles/configure-custom-setting/configs/*"
  tags:
    - asterisk-configure

- name: Copy agi files to /var/lib/asterisk/agi-bin/ (force overwrite)
  copy:
    src: "{{ item }}"
    dest: "/var/lib/asterisk/agi-bin/{{ item | basename }}"
    owner: asterisk
    group: asterisk
    mode: "0755"
    force: yes
  with_fileglob:
    - "roles/configure-custom-setting/agi-bins/*"
  tags:
    - asterisk-agi-bin

- name: Change permissions of Asterisk-related files and directories
  remote_user: root
  shell: "chmod -R 750 /var/{lib,log,run,spool}/asterisk /usr/lib/asterisk /etc/asterisk"
  args:
    executable: /bin/bash
  tags:
    - asterisk
    - system

- name: Reload FreePBX
  remote_user: root
  shell: fwconsole reload
  tags:
    - freepbx
    - asterisk
